language: python
python: "3.8"
services:
  - docker

before_script: 
  - pip install docker-compose
  - psql -c 'create database db;' -U postgres
  - psql -c 'create database app;' -U postgres

script:
  - docker-compose run app python manage.py test && flake8