language: python
python: "3.8"
services:
  - docker



before_install:
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update
  - pip install docker-compose

script:
  - docker-compose run app python manage.py test && flake8